version: '3'

services:
  worker:
    build: .
    image: bot
    restart: unless-stopped
    pull_policy: build
    volumes:
      - ./database:/app/database
      - ./.wdm:/app/.wdm
    environment:
      - DATABASE_URL=sqlite:////app/database/main.db
      - TELEGRAM_TOKEN=$TELEGRAM_TOKEN
