name: test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.4
    - name: Build
      env:
        DISABLE_COLLECTSTATIC: 1
        TELEGRAM_TOKEN: token
        DATABASE_URL: "sqlite:///:memory:"
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
        make test
