name: telegram-bot-template

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.10
    - name: Build
      env:
        DISABLE_COLLECTSTATIC: 1
        TELEGRAM_TOKEN: token
        DATABASE_URL: "sqlite:///:memory:"
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
        make test
